#
# Module manifest for module 'SharedDscConfig'
#
# Generated by: Gael
#
# Generated on: 08/06/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Shared1.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '2a6cb10a-4577-4577-4577-65ce32c38c03'

# Author of this module
Author = 'Gael Colas'

# Company or vendor of this module
CompanyName = 'SynEdgy Ltd'

# Copyright statement for this module
Copyright = '(c) 2017 Gael. All rights reserved.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PSDesiredStateConfiguration')

# DSC resources to export from this module
DscResourcesToExport = @('Shared1')

}

